export const ProjectActionTypes = {
    ADD_PROJECT_MODAL_HIDDEN: 'ADD_PROJECT_MODAL_HIDDEN',
    EDIT_PROJECT_MODAL: 'EDIT_PROJECT_MODAL',
    PROJECT_START: 'PROJECT_START',
    PROJECT_SUCCESS: 'PROJECT_SUCCESS',
    PROJECT_FAILURE: 'PROJECT_FAILURE',
    FETCH_PROJECT : 'FETCH_PROJECT'
}
