export const ProjectActionTypes = {
    ADD_PROJECT_MODAL_HIDDEN: 'ADD_PROJECT_MODAL_HIDDEN',
    EDIT_PROJECT_MODAL: 'EDIT_PROJECT_MODAL',

    FETCH_PROJECT_START: 'FETCH_PROJECT_START',
    FETCH_PROJECT_SUCCESS: 'FETCH_PROJECT_SUCCESS',
    FETCH_PROJECT_FAILURE: 'FETCH_PROJECT_FAILURE',

    SWITCH_PROJECT_DROPDOWN_HIDDEN: 'SWITCH_PROJECT_DROPDOWN_HIDDEN',

    TOGGLE_BURGER_MENU: 'TOGGLE_BURGER_MENU'
};
