export const TaskActionTypes = {
    TOGGLE_EDIT_TASK: 'TOGGLE_EDIT_TASK',
    TOGGLE_ADD_TASK: 'TOGGLE_ADD_TASK',
    FETCH_TASKS_BY_PROJECT_START : 'FETCH_TASKS_BY_PROJECT_START',
    FETCH_TASKS_BY_PROJECT_SUCCESS : 'FETCH_TASKS_BY_PROJECT_SUCCESS',
    FETCH_TASKS_BY_PROJECT_FAILURE : 'FETCH_TASKS_BY_PROJECT_FAILURE',
};
