export const TaskActionTypes = {
    TOGGLE_EDIT_TASK: 'TOGGLE_EDIT_TASK',
    TOGGLE_ADD_TASK: 'TOGGLE_ADD_TASK',
    FETCH_TASKS_START : 'FETCH_TASKS_START',
    FETCH_TASKS_SUCCESS : 'FETCH_TASKS_SUCCESS',
    FETCH_TASKS_FAILURE : 'FETCH_TASKS_FAILURE',
};
